### ISSUE TITLE
The uploadBitcode, uploadSymbols options are always true.

### ISSUE THREAD

**Issue by taehoon-jung** [fastlane/gym#136] opened 2015-10-30 09:17 UTC
Hello,

Recently I applied gym to my project. I modified all scripts.
I am very satisfied with gym. Thank you.

But I found a something when I ran gym with options.

### Issue 

I ran `gym` with `include_bitcode` and `include_symbols` options.
`$ gym --include_bitcode false --include_symbols false`

Building and exporting binary are succeed but I found a log about `exportOptionsPlist` on console.
```
[18:07:09]: Successfully stored the archive. You can find it in the Xcode Organizer.
[18:07:09]: /usr/bin/xcrun xcodebuild -exportArchive -exportOptionsPlist '/tmp/gym_config_1446196029.plist' -archivePath '/Users/user/Library/Developer/Xcode/Archives/2015-10-30/ProductName 2015-10-30 18.03.14.xcarchive' -exportPath '/tmp/1446196029'
```

So I checked the file. 
`$cat /tmp/gym_config_1446196029.plist`
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>method</key>
	<string>app-store</string>
	<key>uploadBitcode</key>
	<true/>
	<key>uploadSymbols</key>
	<true/>
</dict>
</plist>
```

All values of option are `true`. 
Is it right?

**Comment by KrauseFx** [comment] 2015-10-30 16:57
Thanks - I can reproduce the issue, working on a fix now :+1:

**Comment by KrauseFx** [comment] 2015-10-30 17:12
Unfortunately this is related to https://github.com/fastlane/fastlane_core/commit/fddc4fefa7f722bc654717ea2a8be593ea5cd5cb. Right now it's only possible to pass the value using `fastlane` - I want to do a rewrite on how command line parameters work, but this will require some work...

**Comment by taehoon-jung** [comment] 2015-10-31 10:22
Thanks. I hope it will fix soon. :)

**Comment by nijindal** [comment] 2015-11-28 21:18
@KrauseFx Is there anyway right now to pass uploadSymbols as false ?

**Comment by KrauseFx** [comment] 2015-12-01 03:22
@nijindal Yes, using `fastlane` it's possible: `gym(something: false)`

**Comment by KrauseFx** [comment] 2016-02-15 15:12
We recently updated `gym` to support this, make sure to update using `[sudo] gem update fastlane` and try again using `--option_name true` of `--option_name false`

**Comment by sungjin-woo** [comment] 2016-02-24 03:15
I updated `fastlane` and `fastlane_core`.
But `--include_bitcode false` options still does work as `true`.

```
fastlane (1.63.0)
fastlane_core (0.36.7, 0.36.1)
gym (1.6.1, 1.6.0, 1.5.0)
```

```
+----------------------+-----------------------------------------------------------+
|                              Summary for gym 1.6.1                               |
+----------------------+-----------------------------------------------------------+
| workspace            | ../Workspace.xcworkspace                                   |
| scheme               | Workspace_TS                                               |
| clean                | true                                                      |
| output_directory     | ./../distribution/ts                                      |
| output_name          | Workspace-5b2759b                              |
| configuration        | TS                                                        |
| silent               | false                                                     |
| include_symbols      | true                                                      |
| include_bitcode      | true                                                      |
| use_legacy_build_api | false                                                     |
| export_method        | enterprise                                                |
| archive_path         | ../distribution/ts/WWorkspace-5b2759b.xcarchive |
| buildlog_path        | ./../distribution/ts/logs                                 |
| destination          | generic/platform=iOS                                      |
+----------------------+-----------------------------------------------------------+

```

**Comment by mfurtak** [comment] 2016-02-24 19:23
@sungjin-woo Unfortunately because of a limitation of our command line option parsing, boolean flags like `--include_bitcode` can't be controlled with a trailing value like 'true' or 'false'. Just including the `--include_bitcode` flag makes the value `true`. Our current documentation is wrong with regards to this behavior, and one side or the other should be fixed.

As far as I can tell, because of a separate problem with our configuration file handling, specifying the following in your `Gymfile` also **won't work** (but it really should :frowning:) :

```ruby
include_bitcode false
include_symbols false
```

As a short-term work around, the only thing I found that _did successfully communicate_ `false` values for these options was the following `Gymfile`:

```ruby
include_bitcode 'false'
include_symbols 'false'
```

This gets me a `-exportOptionsPlist` like:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>method</key>
	<string>app-store</string>
	<key>uploadBitcode</key>
	<false/>
	<key>uploadSymbols</key>
	<false/>
</dict>
</plist>
```

This is an ugly work around, but please let me know if it unblocks you for the time being. :+1:

**Comment by fastlane-bot-helper** [comment] 2016-03-07 19:49
This issue was migrated to https://github.com/fastlane/fastlane/issues/1846. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:

**Closed by fastlane-bot-helper** 2016-03-07 19:49 UTC
Labels: migrated
