### ISSUE TITLE
Gym command gets stuck and never ends

### ISSUE THREAD

**Issue by calclavia** [fastlane/gym#171] opened 2015-12-29 07:21 UTC
I typed the following command into terminal:

```
gym -p 'platforms/ios/app.xcodeproj' --scheme app --export_method ad-hoc -o build/ios -e scripts/ekko_ad_hoc.mobileprovision -c
```

The command gets stuck after it prints this line. It stalls and never finishes:
```
xcrun xcodebuild -list -project 'platforms/ios/app.xcodeproj'
```

I tried typing the following into the terminal:
```
xcrun xcodebuild -list -project 'platforms/ios/app.xcodeproj'
```

It correctly lists out the target of the xcode project. I'm using Cordova to generate the xcodeproject file.

Using gym v1.2.0
System: Mac OS X El Capitan 10.11.2

**Comment by lacostej** [comment] 2016-01-07 18:04
Duplicate of #143

**Comment by calclavia** [comment] 2016-01-07 18:14
I solved it. It seems like adding "sudo" in front of the command will cause it to fail. Not adding sudo will allow it to work.

**Comment by lacostej** [comment] 2016-02-22 19:01
@calclavia The latest fastlane_core now supports modifying the timeout.
Please update using `sudo gem update fastlane_core` and let us know if that fixes this issue ! Thanks

**Comment by KrauseFx** [comment] 2016-02-23 02:50
Thanks for updating the issue @lacostej :+1:

**Comment by fastlane-bot-helper** [comment] 2016-03-07 19:46
This issue was migrated to https://github.com/fastlane/fastlane/issues/1832. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:

**Closed by fastlane-bot-helper** 2016-03-07 19:46 UTC
Labels: migrated
